---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, fig.cap="Latest wave in Delta.", out.extra="class=external",  fig.width=12, fig.height=6, message=FALSE, echo=FALSE, warning=FALSE}
library(knitr)

library(dplyr)

library(plotly)
library(zoo) # moving averages
library(RcppRoll) # running total
# https://github.com/MoH-Malaysia/covid19-public?s=08 
# https://github.com/CITF-Malaysia/citf-public 

# pop
pop <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/static/population.csv")

# msia dataset
msia <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_malaysia.csv")
msia$date <- as.Date(msia$date)
msia <- msia %>% mutate(new_cases_relative = cases_new/(pop[1,3]/100000),
                        ma7_new_cases_relative =  rollmean(new_cases_relative, k = 7, fill = NA)
                        )
msia <- msia %>% filter(date>as.Date("2021-01-01"))
write.csv(msia, "ss_cases_malaysia.csv")


# new case relative to pop
p <- plot_ly(msia, x = ~as.Date(date), y = ~round(ma7_new_cases_relative,1), type = 'scatter', 
             name = ' 7-day average',
             mode = "lines", line = list(color = "#2F8DA3"), opacity = 0.71)
p <- p %>% add_trace(msia, x = ~as.Date(date), y = ~round(new_cases_relative,1), type = 'scatter', name = 'Case rate', mode = "lines", line = list(color = "#2F8DA3", dash = 'dot'), opacity = 0.51)


p <- p %>%  layout(title = list(text = 'Case rate Malaysia', font = list(size = 14)),
                   xaxis = list(
                     title = "",
                     tickfont = list(
                       size = 11)),
                   yaxis = list(
                     title = 'Cases per 100K people',
                     titlefont = list(
                       size = 13),
                     tickfont = list(
                       size = 14),
                     range = c(-40,100)),
                   legend = list(x = 0, y = 1, bgcolor = 'rgba(255, 255, 255, 0)', bordercolor = 'rgba(255, 255, 255, 0)'),
                   barmode = 'group', bargap = 0.15, bargroupgap = 0.1)
p

```
p <- p %>%  add_trace(msia, x = ~as.Date(date), y = ~round(ma7_new_cases_relative,1), type = 'scatter', 
                      name = '7-day average',
                      mode = "lines", line = list(color = "crimson"), opacity = 0.51)

